### ISSUE TITLE
Spectate translating lines not working "%PLAYER1% %PLAYER2%"

### ISSUE THREAD

**Issue by x1p** [Trophonix/TradePlus#21]
The default translation lines:
```
spectate:
  message: '&6&l(!) &e%PLAYER1% &6and &e%PLAYER2% &6have started a trade %NEWLINE%&6&l(!)
    &6Type &e/tradeplus spectate %PLAYER1% %PLAYER2% &6to spectate'
  hover: '&6&lClick here to spectate this trade'
```
do not work.
I tried translating it too, but can't get it to work.
![screenshot_20181028_124654](https://user-images.githubusercontent.com/28690790/47615482-993f6200-daaf-11e8-9a93-5d03ad4d0c94.png)
