### ISSUE TITLE
Spectate message translation

### ISSUE THREAD

**Issue by x1p** [Trophonix/TradePlus#22]
Just tried the latest release 3.11 but it still contains the bug. It totally ignores the
```
spectate:
  message: '&6&l(!) &e%PLAYER1% &6and &e%PLAYER2% &6have started a trade %NEWLINE%&6&l(!)
    &6Type &e/tradeplus spectate %PLAYER1% %PLAYER2% &6to spectate'
  hover: '&6&lClick here to spectate this trade'
```
Issue #21 is still present. Since this issue was closed, hereby a new one to keep this on the agenda.
