### ISSUE TITLE
[3.72.3][1.15.2] NEWLINE modifier not apply on some case

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [Trophonix/TradePlus#56]
`lang.yml`  

```
cancelled: ''
trade-complete: ''
```

Add `%NEWLINE%` in this option will not work, just show `aaa%NEWLINE%bbb`  
Other option `NEWLINE` work fine, just this not work

`config.yml`

```
request:
  sent: ''
received:
    text: ''
errors:
  within-range:
    same-world: ''
  no-cross-world: ''
  player-not-found: ''
  self-trade: ''

...Many other
```

Are all not work with `\n` or `%NEWLINE%` modifier.
